name: Run tests on new or changed files

on:
  pull_request:
    types: [synchronize, opened, ready_for_review]
    paths:
      - "**_use_case.dart"
      - "**_data.dart"
      - "**_entity.dart"
      - "**_use_case_test.dart"
      - "**_data_spy.dart"
      - "**_entity_test.dart"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get flutter and cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.8"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:version:-:hash:"
